--- 
title: "Becoming a Theory Wonk: Notes, Proofs and Pain"
author: "Lachlan Astfalck"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output:
  bookdown::bs4_book:
      theme:
        bootswatch: sandstone
  bookdown::gitbook:
    split_by: "section"
    config:
      sharing: null
    includes:
      in_header: macros.html
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: true
github-repo: rstudio/bookdown-demo
description: "This is a"
---

# Overture {-}

<!-- I am not a mathematician or a statistician by training. You may be forgiven for thinking otherwise, given my current role and my recent publications in theoretical statistical journals.  -->
I have no formal education in the mathematical sciences and have, for the most part, learned these topics by myself, and often by mistake. In trying to understand the machinery that underpins modern statistics, I found myself attempting to learn all of mathematics at once: analysis, probability, topology, measure theory, and the list goes on. Unsurprisingly, this approach was both inefficient and confusing. Over time, I realised I needed a single place to organise the ideas that recur in my work and studies. This document is that attempt: an incomplete and evolving encyclopedia of mathematical notions that I've found myself returning to. The focus here is on mathematical statistics, that dark crevice of mathematics too applied for the pure mathematicians, and too theoretical for the applied statisticians. The exposition is informal and unapologetically tailored to my own needs. When I include proofs, I do so with more steps and commentary than one might find in a standard textbook. Perhaps I'm slow, but the tersity of proofs confined to print media often assumes an ability greater than mine.

For the moment, I have grouped these writings under the following loose banners. Mathematical statistics is messy and does not follow a linear progression, but rather is a braid of ideation. As such, certain topics are difficult to allocate, and where this is the case I have put them where I best understand them.

* **Analysis** - The study of the machinery that makes calculus behave. Nothing statistical lives here, but the tools built in analysis quietly underpin nearly everything we do later.
* **Linear Algebra and Functional Analysis** — The language of vectors and transformations at infinity. The unspoken grammar of modern statistics.
* **Measure Theory** - The formal machinery for assigning 'size' to sets and probability to events. Often needlessly abstract, but undeniably elegant. Once you surrender to probability as a measure, you can ignore the 'frequentist vs Bayesian' noise.
* **Statistical Asymptotics** - The study of what happens to estimators and models when the data grow without bound. A necessary fiction of rigour and delusion.
* **Weakly Dependent Processes** - Time series and spatial processes that cling to independence just tightly enough to ruin your assumptions, but loosely enough to claim asymptotic validity.


