## Infimum and Supremum {-}

The infimum and supremum generalise the notion of minima and maxima in real-valued sets. They give us upper and lower boundaries without requiring the endpoints to actually exist in the set.

* The **infimum** (or *greatest lower bound*) is the largest number that is still less than or equal to every element of the set.  
* The **supremum** (or *least upper bound*) is the smallest number that is still greater than or equal to every element of the set.

If these bounds happen to be part of the set, then it's just the usual *maximum* or *minimum*. (Don't be a try-hard and write $\inf$ and $\sup$ in your mathematics when dealing with discrete or finite sets.)

Formally, for a set \(A \subset \mathbb{R}\)

- \(u = \sup A\) if  
  (i) \(a \le u\) for all \(a \in A\), and  
  (ii) for every \(\epsilon > 0\), there exists some \(a \in A\) with \(a > u - \epsilon\).

- \(l = \inf A\) if  
  (i) \(l \le a\) for all \(a \in A\), and  
  (ii) for every \(\epsilon > 0\), there exists some \(a \in A\) with \(a < l + \epsilon\).

For instance, if  \(A = (0,1)\), then $\inf A = 0$ and $\sup A = 1$.

I always forget which is which. Noting the latin derivations help: infimum from infimus (inferior) and supremum from supremus (superior). In fact, in older texts (such as Billingsly) these are often directly called the limits inferior and superior.
